### ISSUE TITLE
VSS/VCC could be confusing to noobs.

### ISSUE THREAD

**Issue by Gewurztraminer** [raspberrypi/hats#36]
The ID EEPROM is an old Catalyst part and the datasheet also uses VCC while claiming to be CMOS with not a collector in sight.
Suggest changing to VDD. 
(Yes, I know complementary has PFET source, and it's left over from NMOS, but that's the convention.)

**Comment by P33M** [comment]
Datasheets tend to interchangeably use VCC/VDD to denote +ve digital logic supply pin. The nuances between VCC/VDD are now lost in the mists of time as modern single-function ICs overwhelmingly have a single digital logic supply.

For the part number quoted on the schematic, VCC is the pin name quoted in the datasheet thus schematic and datasheet match.
