### ISSUE TITLE
Spec validity for Pi 2 and 3

### ISSUE THREAD

**Issue by extrapixel** [raspberrypi/hats#38]
well... any information on this? Readme says B+, but what about 2 and 3?

**Comment by RandomlyKnighted** [comment]
There's already a PR to fix this. https://github.com/raspberrypi/hats/pull/32

The information applies to all Raspberry Pis that have a 40 pin header.

**Comment by lurch** [comment]
Fixed by https://github.com/raspberrypi/hats/commit/1f2fbdf09df8c0c63584c633cd8b6e04bf53f841 ?

**Comment by JamesH65** [comment]
Yes
