### ISSUE TITLE
EEPROM emulation.

### ISSUE THREAD

**Issue by diymat** [raspberrypi/hats#43]
Hi. I have a question and think that many people will have the same problem as well. I understand that if a HAT does not not have its own micro - EEPROM is needed. But at the moment I develop couple of HATs with their own ARM uCs. I can emulate the full EEPROM functionality using uC I2C interface & flash memory. Can I do it, or I still need a separate EEPROM IC? Timing is not an issue as the uC is ready much earlier than RPI starts reading the content form it.

**Comment by jimbojr** [comment]
Happy to allow a micro to provide the data - yes this is fine as long as the Pi can't tell the difference!

**Comment by JamesH65** [comment]
@diymat - OK to close?

**Comment by diymat** [comment]
Yes, it is OK to close, thank you, Sorry. After my cataract operation unfortunately I have infected my eye and was unable to use computers :). It
