### ISSUE TITLE
Hat Mechanical Specification updated for RPi Zero

### ISSUE THREAD

**Issue by blsmit5728** [raspberrypi/hats#44]
Could the HAT mechanical specification be updated for the Raspberry Pi Zero and Zero W (i think they would be the same). I have a HAT I have designed, but I cannot call it a HAT due to no Mech Spec for the Zero.

**Comment by RalphCorderoy** [comment]
Also, is a pHAT a /partial/ HAT designed for the Zero?  I understand that's not formally spec'd, but the README.md could do with mentioning them for those that arrive expecting clarification.

**Comment by lurch** [comment]
Fixed by https://github.com/raspberrypi/hats/commit/81e4919b50f46c98ea012c139c3cea940bcd2f7e ?

**Comment by JamesH65** [comment]
I believe so, OK to close?

**Comment by jimbojr** [comment]
Yes I think so
