### ISSUE TITLE
"Device Tree Usage" link results in 404

### ISSUE THREAD

**Issue by markus-k** [raspberrypi/hats#47]
The "device tree usage" link in [devicetree-guide.md](https://github.com/raspberrypi/hats/blob/0b276845f79852950e49466cd51b36be4f50b2c4/devicetree-guide.md) results in a 404. I quickly search the devicetree.org website for the new link, but couldn't find the page.

**Comment by JamesH65** [comment]
ping @pelwell

This should really be reported in the documentation repo.

**Comment by pelwell** [comment]
The link should be redirected to `https://elinux.org/Device_Tree_Usage`.

**Comment by pelwell** [comment]
Fixed - thanks!

**Comment by markus-k** [comment]
Looking good, thank you!
