### ISSUE TITLE
EEPROM file. Hat is using different pins depending in the configuration

### ISSUE THREAD

**Issue by diymat** [raspberrypi/hats#48]
Hi. My hat is connects to the RPi via SPI. It uses only one only four pins - but can be configured to use two SPIs and 5 CS signals. The board does not know what SPI port or which CS signal was chosen. Should I mark all 9 lines as used by the hat?

**Comment by pelwell** [comment]
The need to declare pin usage in the HAT EEPROM has largely been replaced by the embedded DT overlay. Unless you have a specific requirement to configure pins as early as possible you shouldn't need to use the gpios section of the EEPROM.

**Comment by diymat** [comment]
Thank you.  I do not. The RPi starts the communication. Before that my hat is quiet.
