### ISSUE TITLE
CRC format

### ISSUE THREAD

**Issue by uSpike** [raspberrypi/hats#54]
The documentation states that each atom uses "CRC-16-CCITT" as the `crc16` format.  

      2       crc16       CRC-16-CCITT of entire atom (type, count, dlen, data)

According to http://srecord.sourceforge.net/crc16-ccitt.html and http://crcmod.sourceforge.net/crcmod.predefined.html,  `CRC-16-CCITT` has the following attributes:

    Truncated polynomial = 0x1021
    Initial value = 0xFFFF
    Input data is NOT reflected

When looking at the code for calculating the CRC in `eeptypes.h`, I see:

    #define CRC16 0x8005

    ....
    uint16_t getcrc(char* data, unsigned int size) {
    ...
    // item c) reverse the bits

This would suggest that the polynomial is actually 0x8005 and the data is reversed, which corresponds with a plain `CRC-16`.

**Comment by Bitblade** [comment]
I can confirm the algorithm is indeed [plain CRC-16, also known as CRC16-IBM, CRC16-ARC, and several others.](http://reveng.sourceforge.net/crc-catalogue/16.htm#crc.cat.crc-16-arc)

To be exact, said algorithm uses the following parameters: 
`poly=0x8005 init=0x0000 refin=true refout=true xorout=0x0000 check=0xbb3d residue=0x0000`
