### ISSUE TITLE
eepmake: How to access the flashed custom file from user space?

### ISSUE THREAD

**Issue by taudac** [raspberrypi/hats#61]
After flashing a custom file to the ID EEPROM, how do you actually access it later from user space? I thought it would be in `/proc/device-tree/hat/...`, but it is not.

**Comment by pelwell** [comment]
It ought to turn up under `/proc/device-tree/hat/custom_<n>`, where `<n>` is a decimal integer counting up from 0.

Can you post your eeprom.txt file?

**Comment by taudac** [comment]
The issue is no longer reproducible. I am sorry for the noise.

I am building the EEPROM image with:

    eepmake myhat-eeprom.txt myhat.eep myhat.dtbo -c myhat-params.txt

The `myhat-eeprom.txt` file contains no custom data related entries.

I am now able to access the data via `/proc/device-tree/hat/custom_0`.

**Comment by pelwell** [comment]
Cool - you may be the first person to use it in anger.

**Comment by taudac** [comment]
@pelwell Many thanks for your very quick response. It has shown me that I must be doing something wrong.

**Comment by pelwell** [comment]
If you fail to get it working, upload myhat.eep somewhere and I'll have a look.
