### ISSUE TITLE
How can I create /proc/device-tree/hat/custom_0

### ISSUE THREAD

**Issue by rudiratlos** [raspberrypi/hats#66]
How can I create such a node ( /proc/device-tree/hat/custom_0 )?
which contains additional info.

**Comment by pelwell** [comment]
Any parameters appearing after `-c` will be treated as the names of files to be added as custom blobs, e.g.:
```
$ eepmake myhat-eeprom.txt myhat.eep myhat.dtbo -c myhat-custom_0 myhat-custom_1
```

**Comment by rudiratlos** [comment]
How does this file (myhat-custom_0) look like, if I want the following string in the EEprom?
"I was here"

**Comment by pelwell** [comment]
The files should contain _exactly_ what you want to appear in the custom entry.

**Comment by rudiratlos** [comment]
works. Wow didn't thought that things could also be easy.
Thank you
