### ISSUE TITLE
SCL/SDA mixup in designguide.md

### ISSUE THREAD

**Issue by ThomasBarth** [raspberrypi/hats#68]
> Within the set of pins available on the GPIO header, ID_SC and ID_SD (GPIO0/SCL and GPIO1/SDA) are reserved for board detection / identification.

According to https://www.raspberrypi.org/documentation/usage/gpio/ it should be:

> Within the set of pins available on the GPIO header, ID_SC and ID_SD (GPIO0/SDA and GPIO1/SCL) are reserved for board detection / identification.

In addition I would like to propose to also add the pin numbers 27/28 to be more generic.

**Comment by pelwell** [comment]
Thanks - fixed by https://github.com/raspberrypi/hats/commit/894ad72392d9a12615b810df023e29f1d629d80c.
