### ISSUE TITLE
RPi 4B ZVD

### ISSUE THREAD

**Issue by WardBenjamin** [raspberrypi/hats#77]
Hello,

The design guide specifies: 

> Raspberry Pi Model A+, B+, Raspberry Pi 2B and 3B have an 'ideal' reverse current blocking diode (ZVD) circuit on their 5V input.

and also:

> NOTE that the Raspberry Pi 3B+ and Pi Zero and ZeroW do not include an input ZVD. 

Does the Raspberry Pi 4B include an input ZVD?

**Comment by jimbojr** [comment]
Pi4 does not have a ZVD - I've updated the design guide, thanks.
