### ISSUE TITLE
Clarification on back-voltage protection

### ISSUE THREAD

**Issue by gcormier** [raspberrypi/hats#79]
The wording is not clear

`If the add-on board uses any more GPIO connector pins than the first 26 and provides back-powering via the 5V GPIO header pins it is required to...`

Is this in reference to GPIO1-26, or in reference of pins 1-26? I suspect the latter, but would like clarification. It might help to update this wording as well.

**Comment by pelwell** [comment]
"GPIO connector pins" is fairly clear to me - the whole page is about physical pins rather than GPIOs, the only difference to this one mention is the use of the word "connector" rather than "header".
