### ISSUE TITLE
Link to forums is broken

### ISSUE THREAD

**Issue by gregoryleblanc** [raspberrypi/hats#87]
The link to the forums is broken.  Perhaps it should be 
https://forums.raspberrypi.com/viewforum.php?f=45
instead?

https://github.com/raspberrypi/hats/blob/c8a2f630f9d50159d94ad6ad7c24973cdeb7b8f1/README.md?plain=1#L19

**Comment by pelwell** [comment]
Thanks - it should be fixed now.

**Comment by gregoryleblanc** [comment]
Yup, this is fixed.  Thanks much!
