### ISSUE TITLE
eepmake fails with assertion

### ISSUE THREAD

**Issue by matthiesenj** [raspberrypi/hats#88]
Running eepmake on the default eeprom_settings.txt file with just custom_data changed from "c0ffee" to "deadbeef" causes the following error:
> eepmake eeprom_settings.txt eeprom.eep
[eeprom_settings.txt](https://github.com/raspberrypi/hats/files/8325713/eeprom_settings.txt)

Opening file eeprom_settings.txt for read
UUID=72463678-e88b-469d-9be3-e28e2414033f
Done reading
Writing out...
eepmake: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted

eepmake was built and run on raspian/debian 10.11, Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

**Comment by pelwell** [comment]
Wow, that code was... interesting. It should work now, and I've thrown in a slightly more challenging bit of custom_data in the example eeprom_settings.txt.

**Comment by matthiesenj** [comment]
It works with your new test data on a CM4 now.

Thanks!
